#Creating a layer from the Nginx Official Docker Image
FROM nginx
#Adds files from the current working director
COPY . /usr/share/nginx/html
#nginx uses port 80 by default so we expose that port 
EXPOSE 80