# Derived from official mysql image (our base image)
FROM mysql
# Add a database
ENV MYSQL_DATABASE: myDatabase
ENV  MYSQL_ROOT_PASSWORD: Mysql123
# Add the content of the sql-scripts/ directory to your image
# All scripts in docker-entrypoint-initdb.d/ are automatically executed during container startup
COPY  . /docker-entrypoint-initdb.d