#Specifying the Docker version 
version: "3.7"
services: 
  back-end:   # spins up my go code
    container_name: hrprdcts_api  # name of the container in docker
    build:
      context: back-end #name of my folder
    ports: 
       - "8020:8020" #exposing the port my API is listening on
    networks: 
      - backend # connecting all the services
    depends_on: #API won't function unless the database and front end containers spin up
      - database
      - front-end 
#---------------------------------------------
  database:
    environment: 
      MYSQL_DATABASE: products #name of database
      MYSQL_ROOT_PASSWORD: Redventures123
    container_name: hrprdcts_database # name of the container
    build:
      context: database #name of my folder
    ports: 
      - "3308:3306" #the connection in docker is 3308
    networks: 
      - backend
#---------------------------------------------
  front-end:
    container_name: hrprdcts_web
    build:
      context: front-end
    ports:
      - "9090:80" #mapping port 9090 to the web port. 
    networks: 
      - backend
networks: 
  backend: