#Specifying the Docker version 
version: "3.7"
services: 
  back-end:
    container_name: hrprdcts_api
    build:
      context: back-end
      dockerfile: Dockerfile
    ports: 
       - "8020:8020"
    restart: always
    networks: 
      - backend
    depends_on: 
      - database
      - front-end
    tty: true
#---------------------------------------------
  database:
    container_name: hrprdcts_database
    build:
      context: database
      dockerfile: Dockerfile
    hostname: database
    ports: 
      - "3308:3306"
    restart: always
    environment: 
      MYSQL_DATABASE: products
      MYSQL_ROOT_PASSWORD: Redventures123
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
    networks: 
      - backend
#---------------------------------------------
  front-end:
    container_name: hrprdcts_web
    build:
      context: front-end
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    links: 
      - "database"
    restart: always
    networks: 
      - backend
networks: 
  backend:
    driver: "bridge"
